# Generated by Django 5.2.14 on 2026-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(help_text='Imagem do QR Code PIX.', upload_to='payment/')),
                ('pix_code', models.CharField(help_text='Código PIX copia-e-cola (string alfanumérica).', max_length=256)),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configuração de Pagamento',
            },
        ),
    ]
