# Generated by Django 5.2.14 on 2026-05-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Quantidade mínima para ativar o desconto.')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Percentual de desconto (ex.: 10.00 = 10% de desconto).', max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
