# Generated by Django 5.2.14 on 2026-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Token do bot Telegram (ex.: 123456:ABC-DEF…).', max_length=200)),
                ('chat_id', models.CharField(help_text='ID do chat/grupo para onde as notificações serão enviadas.', max_length=80)),
                ('is_enabled', models.BooleanField(default=True, help_text='Desative para pular notificações sem remover as credenciais.')),
            ],
            options={
                'verbose_name': 'Configuração do Telegram',
                'verbose_name_plural': 'Configuração do Telegram',
            },
        ),
    ]
