# Generated by Django 5.2.14 on 2026-05-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_telegramconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(help_text='E-mail da conta SMTP.', max_length=200)),
                ('password', models.CharField(help_text='Senha ou app-password SMTP.', max_length=200)),
                ('from_email', models.EmailField(help_text='Remetente (geralmente igual ao username).', max_length=254)),
                ('to_email', models.CharField(help_text='Destinatário(s). Separe múltiplos com vírgula.', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configuração de E-mail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
