# Generated by Django 5.2.14 on 2026-05-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_emailconfig_order_email_error_order_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_casa',
            field=models.TextField(blank=True, help_text='Número ou identificação da casa.'),
        ),
    ]
