# Generated by Django 5.2.14 on 2026-05-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_customer_address_order_customer_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('retirada', 'Retirar no local'), ('entrega', 'Entregar em casa')], default='retirada', max_length=10),
        ),
    ]
