# Generated by Django 5.2.14 on 2026-05-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('pix', 'PIX')], default='presencial', max_length=10),
        ),
    ]
